### ISSUE TITLE
Issues in parsing java8 date time object with Spring Boot

### ISSUE THREAD

**Issue by pawar-kapil** [FasterXML/jackson-modules-java8#268] opened 2023-03-15 08:56 UTC
After upgrading from springboot 2.4.0 to 2.6.0, we have started recieving this error:
`org.springframework.data.redis.serializer.SerializationException: Could not write JSON: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: MyDTO["createdOn"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: MyDTO["createdOn"])
`.

The objectmapper configurations that I have set are as follows:
```
mapper = new ObjectMapper();
        mapper.registerModule(new com.fasterxml.jackson.datatype.jsr310.JavaTimeModule());
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        mapper.configure(SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS, false);
        ClassLoader classLoader = ObjectMapperContextResolver.class.getClassLoader();
        if (ClassUtils.isPresent("org.hibernate.proxy.HibernateProxy", classLoader)) {

            mapper.registerModule(new com.fasterxml.jackson.datatype.hibernate5.Hibernate5Module().disable(
                            com.fasterxml.jackson.datatype.hibernate5.Hibernate5Module.Feature.USE_TRANSIENT_ANNOTATION));
        }
        mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
```

The versions that I'm using are:
jackson-databind:2.13.0
jackson-datatype-jsr310:2.13.0
spring-boot:2.6.0

**Comment by cowtowncoder** [comment] 2023-03-15 18:07
This looks like a Spring issue with configuration, so you will need to work with Spring support / issue trackers. We do not troubleshoot issues wrt configuration of 3rd party libraries or frameworks, although we work with their maintainers as needed (to help them integrate).

If you could show a Jackson-only reproduction of the issue we could help, but I think here specifically that is not possible.

**Comment by cowtowncoder** [comment] 2023-05-29 20:47
Cannot reproduce without stand-alone test; closing, may be reopened with such test (but recommend going via Spring support route first)

**Closed by cowtowncoder** 2023-05-29 20:47 UTC
Labels: test-needed
