### ISSUE TITLE
Unable to deserialize with 'jackson-module-parameter-names', version: '2.9.4'

### ISSUE THREAD

**Issue by marcofranssen** [FasterXML/jackson-modules-java8#56] opened 2018-02-28 14:28 UTC
We are getting following exception with our multimodule project.

```
Can not construct instance of com.myproject.events.CategoryCreatedEvent: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: N/A; line: -1, column: -1]
```

The project structure looks as following:

```
myproject
`- api
`- events
`- projections
```

Within projections we try to deserialize the event which is published by api via RabbitMQ. To consume those events we are using our own library which contains the pub sub logic. Also this library has the same jackson-module-parameter-names module included and has the `-parameters` compiler argument.

Within the unittests in this rabbitmq project the deserializing is actually working. Within this projections library projects it gives the above error. 

Is there a limitation on using this accross multiple modules?

We are running it using JDK 1.8.0_152.

**Comment by cowtowncoder** [comment] 2018-02-28 19:06
First of all, this is more of a usage question and belongs here:

https://groups.google.com/forum/#!forum/jackson-user

but as to specific question: no, multiple modules are not problematic, the whole idea is that module interface is designed to allow co-operation of components.
My main guesses would be that either parameter name information is not included everywhere due to compiler or IDE; or that parameter name module is not being registered in one place (different `ObjectMapper` being used).

**Comment by cowtowncoder** [comment] 2018-04-10 03:16
Would need a reproduction of the problem to help; closing until then.

**Closed by cowtowncoder** 2018-04-10 03:16 UTC
