### ISSUE TITLE
Parses ISO 8601 timestamp that ends with Z into LocalDateTime

### ISSUE THREAD

**Issue by saibotma** [FasterXML/jackson-modules-java8#213] opened 2021-04-09 12:12 UTC
Jackson does not raise an error when parsing JSON containing a date time ending with "Z" like `1970-01-01T12:00:00Z` into `LocalDateTime`.
According to the documentation of `DateTimeFormatter.ISO_LOCAL_DATE_TIME` it should only parse date times without "Z" or any other offset.

**Comment by cowtowncoder** [comment] 2021-04-09 17:58
This is due to inter-operability, I think. Some frameworks/libraries unfortunately insist on adding zulu-timezone, incorrectly, yes, and many users before handling this gracefully.
This lenient handling is the default. I think there is a way to disable this by forcing "strict" handling either just for `LocalDateTime` type (or specific property), or with the general default setting.

Tests show choices of:

```
    final static class StrictWrapper {
        @JsonFormat(pattern="yyyy-MM-dd HH:mm",
                lenient = OptBoolean.FALSE)
        public LocalDateTime value;
    }
```

```
    ObjectMapper mapper = new ObjectMapper();
    // global default for all types
    mapper.setDefaultLeniency(false);

    // or
    mapper.configOverride(LocalDateTime.class)
            .setFormat(JsonFormat.Value.forLeniency(Boolean.FALSE));
```

**Comment by saibotma** [comment] 2021-04-14 05:38
All the options you mentioned don't work for me. Could it be because I am using "jackson-module-kotlin" (2.11.0)?

**Comment by cowtowncoder** [comment] 2021-07-09 01:08
At this point a reproduction with 2.12(.4) would be needed to show that strict handling does not throw exception in this case.
Closing but may be reopened with a repro like unit test.

**Closed by cowtowncoder** 2021-07-09 01:08 UTC
Labels: test-needed
