### ISSUE TITLE
Cannot parse ISO 8601 "style" date that does not contain colon in offset

### ISSUE THREAD

**Issue by mattbroekhuis** [FasterXML/jackson-modules-java8#39] opened 2017-08-23 15:33 UTC
java.util.Date works fine, but does not work for the new time types when the offset is +0500 vs +05:00

```
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.util.Date;

public class JavaDateTest {
    private static final String json = "{\"happyHour\": \"2016-01-01T00:00:00.000+5000\"}";

    private ObjectMapper objectMapper;

    @Before
    public void setup() {
        objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
    }

    @Test
    public void date() throws IOException {
        objectMapper.readValue(json, DtoWithDate.class); //pass
    }

    @Test
    public void instant() throws IOException {
        objectMapper.readValue(json, DtoWithInstant.class); //fail
    }

    @Test
    public void offset() throws IOException {
        objectMapper.readValue(json, DtoWithOffsetDateTime.class); //fail
    }

    private static class DtoWithDate {
        private Date happyHour;

        public Date getHappyHour() {
            return happyHour;
        }

        public void setHappyHour(Date happyHour) {
            this.happyHour = happyHour;
        }
    }

    private static class DtoWithInstant {
        private Instant happyHour;

        public Instant getHappyHour() {
            return happyHour;
        }

        public void setHappyHour(Instant happyHour) {
            this.happyHour = happyHour;
        }
    }

    private static class DtoWithOffsetDateTime {
        private OffsetDateTime happyHour;

        public OffsetDateTime getHappyHour() {
            return happyHour;
        }

        public void setHappyHour(OffsetDateTime happyHour) {
            this.happyHour = happyHour;
        }
    }
}



```

**Comment by brenuart** [comment] 2017-08-24 11:08
Seems to be duplicate of https://github.com/FasterXML/jackson-modules-java8/issues/38

**Comment by cowtowncoder** [comment] 2018-01-07 04:46
Yes, I think this is dup of #38. Closing.

**Closed by cowtowncoder** 2018-01-07 04:46 UTC
