### ISSUE TITLE
Inconsistent serialization/deserialization for OffsetDateTime

### ISSUE THREAD

**Issue by bcalmac** [FasterXML/jackson-modules-java8#53] opened 2018-02-06 16:55 UTC
With WRITE_DATES_AS_TIMESTAMPS disabled, the serialization of OffsetDateTime preserves the offset, while the deserialization discards it (makes the offset 0 as UTC). The unit test below converts an a OffsetDateTime to JSON and back to OffsetDateTime. It fails because of this inconsistency.

NOTE: The OffsetDateTime corresponds to the same Instant, but it's not equal to the original OffsetDateTime as defined by equals(), which takes the offset into account.

```java
    @Test
    public void offsetDateTimeToJsonAndBack() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper()
                .registerModule(new JavaTimeModule())
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

        OffsetDateTime expected = OffsetDateTime.now();
        String actualString = objectMapper.writeValueAsString(expected);
        System.out.println(actualString); // 2018-02-06T08:37:33.557-08:00
        OffsetDateTime actual = objectMapper.readValue(actualString, OffsetDateTime.class);
        assertEquals(expected, actual);
    }
``` 
Failure:
```
java.lang.AssertionError:
Expected :2018-02-06T08:37:33.557-08:00
Actual   :2018-02-06T16:37:33.557Z
```

A similar test using parse() and toString() works fine:

```java
    @Test
    public void offsetDateTimeToStringAndBack() {
        OffsetDateTime expected = OffsetDateTime.now();
        String actualString = expected.toString();
        System.out.println(actualString);
        OffsetDateTime actual = OffsetDateTime.parse(actualString);
        assertEquals(expected, actual);
    }
```

**Comment by oliverdozsa** [comment] 2018-08-21 15:39
Hello. 
Could it be the problem?
DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE

**Comment by bric3** [comment] 2019-02-07 14:02
@oliverdozsa It seems to have done the job. Thanks for the tip !

```
new ObjectMapper().disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
```

**Comment by igorbolic** [comment] 2019-03-08 15:52
Deserialization feature worked for me. When I'm using the `ZonedDateTime` I had to enable the `SerializationFeature.WRITE_DATES_WITH_ZONE_ID` as well:

```java
ObjectMapper mapper = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
            .enable(SerializationFeature.WRITE_DATES_WITH_ZONE_ID);
```

**Comment by yngvark** [comment] 2019-03-11 12:04
Is this by design or a bug? It seems to me as a bug.

To me, having ADJUST_DATES_TO_CONTEXT_TIME_ZONE enabled, I would assume (given the name of that constant) that if my code reads a datetime in timezone +5, but my local timezone is +4, it would get converted to +4. But as @bcalmac shows, it gets converted to +0 / UTC.

Also, the javadoc (https://jar-download.com/javaDoc/com.fasterxml.jackson.core/jackson-databind/2.9.5/com/fasterxml/jackson/databind/DeserializationFeature.html#ADJUST_DATES_TO_CONTEXT_TIME_ZONE) states that 

> Feature that specifies whether context provided TimeZone (DeserializationContext.getTimeZone() should be **used to adjust** Date/Time values on deserialization.

It does not state that it gets converted to UTC.

**Comment by cowtowncoder** [comment] 2019-08-13 20:37
"Context time zone" means whatever Jackson-configured timezone is, and by default Jackson DOES  NOT use "local time zone" (or offset) but UTC. So if you want to use local tz, configure `ObjectMapper` with it.

At this point I am not sure there is a problem any more (comments wrt settings appear correct to me), so closing. There are newer issues in this area, but if something is missing, please re-file with up-to-date test.

**Closed by cowtowncoder** 2019-08-13 20:37 UTC

**Comment by spyro2000** [comment] 2020-11-26 17:51
Stumbled across that today. Caused serious issues for that. Why is the default setting to destroy information in a mapping framework? This is completly beyond anyone I spoke to. Why should 2015-01-23T16:21:00+08:00 be parsed with an Offset of 0 hours? A mapped should always survive a simple roundtrimp value -> json -> value without information be thrown away without reason.

Please just use OffsetDateTime.toString() and OffsetDateTime.parse() and everything works as expected.
